/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: comm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "comm.pb-c.h"
void   livepb__comm__cs_comm_heartbeat_req__init
                     (Livepb__Comm__CsCommHeartbeatReq         *message)
{
  static const Livepb__Comm__CsCommHeartbeatReq init_value = LIVEPB__COMM__CS_COMM_HEARTBEAT_REQ__INIT;
  *message = init_value;
}
size_t livepb__comm__cs_comm_heartbeat_req__get_packed_size
                     (const Livepb__Comm__CsCommHeartbeatReq *message)
{
  assert(message->base.descriptor == &livepb__comm__cs_comm_heartbeat_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__comm__cs_comm_heartbeat_req__pack
                     (const Livepb__Comm__CsCommHeartbeatReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__comm__cs_comm_heartbeat_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__comm__cs_comm_heartbeat_req__pack_to_buffer
                     (const Livepb__Comm__CsCommHeartbeatReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__comm__cs_comm_heartbeat_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Comm__CsCommHeartbeatReq *
       livepb__comm__cs_comm_heartbeat_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Comm__CsCommHeartbeatReq *)
     protobuf_c_message_unpack (&livepb__comm__cs_comm_heartbeat_req__descriptor,
                                allocator, len, data);
}
void   livepb__comm__cs_comm_heartbeat_req__free_unpacked
                     (Livepb__Comm__CsCommHeartbeatReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__comm__cs_comm_heartbeat_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__comm__sc_comm_heartbeat_res__init
                     (Livepb__Comm__ScCommHeartbeatRes         *message)
{
  static const Livepb__Comm__ScCommHeartbeatRes init_value = LIVEPB__COMM__SC_COMM_HEARTBEAT_RES__INIT;
  *message = init_value;
}
size_t livepb__comm__sc_comm_heartbeat_res__get_packed_size
                     (const Livepb__Comm__ScCommHeartbeatRes *message)
{
  assert(message->base.descriptor == &livepb__comm__sc_comm_heartbeat_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__comm__sc_comm_heartbeat_res__pack
                     (const Livepb__Comm__ScCommHeartbeatRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__comm__sc_comm_heartbeat_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__comm__sc_comm_heartbeat_res__pack_to_buffer
                     (const Livepb__Comm__ScCommHeartbeatRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__comm__sc_comm_heartbeat_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Comm__ScCommHeartbeatRes *
       livepb__comm__sc_comm_heartbeat_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Comm__ScCommHeartbeatRes *)
     protobuf_c_message_unpack (&livepb__comm__sc_comm_heartbeat_res__descriptor,
                                allocator, len, data);
}
void   livepb__comm__sc_comm_heartbeat_res__free_unpacked
                     (Livepb__Comm__ScCommHeartbeatRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__comm__sc_comm_heartbeat_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__comm__cs_comm_login_req__init
                     (Livepb__Comm__CsCommLoginReq         *message)
{
  static const Livepb__Comm__CsCommLoginReq init_value = LIVEPB__COMM__CS_COMM_LOGIN_REQ__INIT;
  *message = init_value;
}
size_t livepb__comm__cs_comm_login_req__get_packed_size
                     (const Livepb__Comm__CsCommLoginReq *message)
{
  assert(message->base.descriptor == &livepb__comm__cs_comm_login_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__comm__cs_comm_login_req__pack
                     (const Livepb__Comm__CsCommLoginReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__comm__cs_comm_login_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__comm__cs_comm_login_req__pack_to_buffer
                     (const Livepb__Comm__CsCommLoginReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__comm__cs_comm_login_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Comm__CsCommLoginReq *
       livepb__comm__cs_comm_login_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Comm__CsCommLoginReq *)
     protobuf_c_message_unpack (&livepb__comm__cs_comm_login_req__descriptor,
                                allocator, len, data);
}
void   livepb__comm__cs_comm_login_req__free_unpacked
                     (Livepb__Comm__CsCommLoginReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__comm__cs_comm_login_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__comm__sc_comm_login_res__init
                     (Livepb__Comm__ScCommLoginRes         *message)
{
  static const Livepb__Comm__ScCommLoginRes init_value = LIVEPB__COMM__SC_COMM_LOGIN_RES__INIT;
  *message = init_value;
}
size_t livepb__comm__sc_comm_login_res__get_packed_size
                     (const Livepb__Comm__ScCommLoginRes *message)
{
  assert(message->base.descriptor == &livepb__comm__sc_comm_login_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__comm__sc_comm_login_res__pack
                     (const Livepb__Comm__ScCommLoginRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__comm__sc_comm_login_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__comm__sc_comm_login_res__pack_to_buffer
                     (const Livepb__Comm__ScCommLoginRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__comm__sc_comm_login_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Comm__ScCommLoginRes *
       livepb__comm__sc_comm_login_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Comm__ScCommLoginRes *)
     protobuf_c_message_unpack (&livepb__comm__sc_comm_login_res__descriptor,
                                allocator, len, data);
}
void   livepb__comm__sc_comm_login_res__free_unpacked
                     (Livepb__Comm__ScCommLoginRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__comm__sc_comm_login_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define livepb__comm__cs_comm_heartbeat_req__field_descriptors NULL
#define livepb__comm__cs_comm_heartbeat_req__field_indices_by_name NULL
#define livepb__comm__cs_comm_heartbeat_req__number_ranges NULL
const ProtobufCMessageDescriptor livepb__comm__cs_comm_heartbeat_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Comm__CsCommHeartbeatReq),
  0,
  livepb__comm__cs_comm_heartbeat_req__field_descriptors,
  NULL, /* CODE_SIZE */
  0,  livepb__comm__cs_comm_heartbeat_req__number_ranges,
  (ProtobufCMessageInit) livepb__comm__cs_comm_heartbeat_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livepb__comm__sc_comm_heartbeat_res__field_descriptors[1] =
{
  {
    NULL, /* CODE_SIZE */
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Livepb__Comm__ScCommHeartbeatRes, has_heartbeat_at),
    offsetof(Livepb__Comm__ScCommHeartbeatRes, heartbeat_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const ProtobufCIntRange livepb__comm__sc_comm_heartbeat_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor livepb__comm__sc_comm_heartbeat_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Comm__ScCommHeartbeatRes),
  1,
  livepb__comm__sc_comm_heartbeat_res__field_descriptors,
  NULL, /* CODE_SIZE */
  1,  livepb__comm__sc_comm_heartbeat_res__number_ranges,
  (ProtobufCMessageInit) livepb__comm__sc_comm_heartbeat_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livepb__comm__cs_comm_login_req__field_descriptors[4] =
{
  {
    NULL, /* CODE_SIZE */
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Livepb__Comm__CsCommLoginReq, has_login_type),
    offsetof(Livepb__Comm__CsCommLoginReq, login_type),
    &livepb__comm__login_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Livepb__Comm__CsCommLoginReq, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Livepb__Comm__CsCommLoginReq, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Livepb__Comm__CsCommLoginReq, stream_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const ProtobufCIntRange livepb__comm__cs_comm_login_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor livepb__comm__cs_comm_login_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Comm__CsCommLoginReq),
  4,
  livepb__comm__cs_comm_login_req__field_descriptors,
  NULL, /* CODE_SIZE */
  1,  livepb__comm__cs_comm_login_req__number_ranges,
  (ProtobufCMessageInit) livepb__comm__cs_comm_login_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livepb__comm__sc_comm_login_res__field_descriptors[1] =
{
  {
    NULL, /* CODE_SIZE */
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Livepb__Comm__ScCommLoginRes, has_errcode),
    offsetof(Livepb__Comm__ScCommLoginRes, errcode),
    &livepb__comm__login_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const ProtobufCIntRange livepb__comm__sc_comm_login_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor livepb__comm__sc_comm_login_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Comm__ScCommLoginRes),
  1,
  livepb__comm__sc_comm_login_res__field_descriptors,
  NULL, /* CODE_SIZE */
  1,  livepb__comm__sc_comm_login_res__number_ranges,
  (ProtobufCMessageInit) livepb__comm__sc_comm_login_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue livepb__comm__login_type__enum_values_by_number[2] =
{
  { NULL, NULL, 0 }, /* CODE_SIZE */
  { NULL, NULL, 1 }, /* CODE_SIZE */
};
static const ProtobufCIntRange livepb__comm__login_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumDescriptor livepb__comm__login_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  2,
  livepb__comm__login_type__enum_values_by_number,
  0, NULL, /* CODE_SIZE */
  1,
  livepb__comm__login_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue livepb__comm__login_code__enum_values_by_number[4] =
{
  { NULL, NULL, 0 }, /* CODE_SIZE */
  { NULL, NULL, 16 }, /* CODE_SIZE */
  { NULL, NULL, 17 }, /* CODE_SIZE */
  { NULL, NULL, 18 }, /* CODE_SIZE */
};
static const ProtobufCIntRange livepb__comm__login_code__value_ranges[] = {
{0, 0},{16, 1},{0, 4}
};
const ProtobufCEnumDescriptor livepb__comm__login_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  4,
  livepb__comm__login_code__enum_values_by_number,
  0, NULL, /* CODE_SIZE */
  2,
  livepb__comm__login_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
