/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: player.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "player.pb-c.h"
void   livepb__player__sc_player_no_stream_notify__init
                     (Livepb__Player__ScPlayerNoStreamNotify         *message)
{
  static const Livepb__Player__ScPlayerNoStreamNotify init_value = LIVEPB__PLAYER__SC_PLAYER_NO_STREAM_NOTIFY__INIT;
  *message = init_value;
}
size_t livepb__player__sc_player_no_stream_notify__get_packed_size
                     (const Livepb__Player__ScPlayerNoStreamNotify *message)
{
  assert(message->base.descriptor == &livepb__player__sc_player_no_stream_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__player__sc_player_no_stream_notify__pack
                     (const Livepb__Player__ScPlayerNoStreamNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__player__sc_player_no_stream_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__player__sc_player_no_stream_notify__pack_to_buffer
                     (const Livepb__Player__ScPlayerNoStreamNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__player__sc_player_no_stream_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Player__ScPlayerNoStreamNotify *
       livepb__player__sc_player_no_stream_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Player__ScPlayerNoStreamNotify *)
     protobuf_c_message_unpack (&livepb__player__sc_player_no_stream_notify__descriptor,
                                allocator, len, data);
}
void   livepb__player__sc_player_no_stream_notify__free_unpacked
                     (Livepb__Player__ScPlayerNoStreamNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__player__sc_player_no_stream_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__player__sc_player_disconn_from_upstream_notify__init
                     (Livepb__Player__ScPlayerDisconnFromUpstreamNotify         *message)
{
  static const Livepb__Player__ScPlayerDisconnFromUpstreamNotify init_value = LIVEPB__PLAYER__SC_PLAYER_DISCONN_FROM_UPSTREAM_NOTIFY__INIT;
  *message = init_value;
}
size_t livepb__player__sc_player_disconn_from_upstream_notify__get_packed_size
                     (const Livepb__Player__ScPlayerDisconnFromUpstreamNotify *message)
{
  assert(message->base.descriptor == &livepb__player__sc_player_disconn_from_upstream_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__player__sc_player_disconn_from_upstream_notify__pack
                     (const Livepb__Player__ScPlayerDisconnFromUpstreamNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__player__sc_player_disconn_from_upstream_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__player__sc_player_disconn_from_upstream_notify__pack_to_buffer
                     (const Livepb__Player__ScPlayerDisconnFromUpstreamNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__player__sc_player_disconn_from_upstream_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Player__ScPlayerDisconnFromUpstreamNotify *
       livepb__player__sc_player_disconn_from_upstream_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Player__ScPlayerDisconnFromUpstreamNotify *)
     protobuf_c_message_unpack (&livepb__player__sc_player_disconn_from_upstream_notify__descriptor,
                                allocator, len, data);
}
void   livepb__player__sc_player_disconn_from_upstream_notify__free_unpacked
                     (Livepb__Player__ScPlayerDisconnFromUpstreamNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__player__sc_player_disconn_from_upstream_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__player__cs_player_statistics_frame_notify__init
                     (Livepb__Player__CsPlayerStatisticsFrameNotify         *message)
{
  static const Livepb__Player__CsPlayerStatisticsFrameNotify init_value = LIVEPB__PLAYER__CS_PLAYER_STATISTICS_FRAME_NOTIFY__INIT;
  *message = init_value;
}
size_t livepb__player__cs_player_statistics_frame_notify__get_packed_size
                     (const Livepb__Player__CsPlayerStatisticsFrameNotify *message)
{
  assert(message->base.descriptor == &livepb__player__cs_player_statistics_frame_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__player__cs_player_statistics_frame_notify__pack
                     (const Livepb__Player__CsPlayerStatisticsFrameNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__player__cs_player_statistics_frame_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__player__cs_player_statistics_frame_notify__pack_to_buffer
                     (const Livepb__Player__CsPlayerStatisticsFrameNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__player__cs_player_statistics_frame_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Player__CsPlayerStatisticsFrameNotify *
       livepb__player__cs_player_statistics_frame_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Player__CsPlayerStatisticsFrameNotify *)
     protobuf_c_message_unpack (&livepb__player__cs_player_statistics_frame_notify__descriptor,
                                allocator, len, data);
}
void   livepb__player__cs_player_statistics_frame_notify__free_unpacked
                     (Livepb__Player__CsPlayerStatisticsFrameNotify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__player__cs_player_statistics_frame_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__player__cs_player_stop_req__init
                     (Livepb__Player__CsPlayerStopReq         *message)
{
  static const Livepb__Player__CsPlayerStopReq init_value = LIVEPB__PLAYER__CS_PLAYER_STOP_REQ__INIT;
  *message = init_value;
}
size_t livepb__player__cs_player_stop_req__get_packed_size
                     (const Livepb__Player__CsPlayerStopReq *message)
{
  assert(message->base.descriptor == &livepb__player__cs_player_stop_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__player__cs_player_stop_req__pack
                     (const Livepb__Player__CsPlayerStopReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__player__cs_player_stop_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__player__cs_player_stop_req__pack_to_buffer
                     (const Livepb__Player__CsPlayerStopReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__player__cs_player_stop_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Player__CsPlayerStopReq *
       livepb__player__cs_player_stop_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Player__CsPlayerStopReq *)
     protobuf_c_message_unpack (&livepb__player__cs_player_stop_req__descriptor,
                                allocator, len, data);
}
void   livepb__player__cs_player_stop_req__free_unpacked
                     (Livepb__Player__CsPlayerStopReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__player__cs_player_stop_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   livepb__player__sc_player_stop_res__init
                     (Livepb__Player__ScPlayerStopRes         *message)
{
  static const Livepb__Player__ScPlayerStopRes init_value = LIVEPB__PLAYER__SC_PLAYER_STOP_RES__INIT;
  *message = init_value;
}
size_t livepb__player__sc_player_stop_res__get_packed_size
                     (const Livepb__Player__ScPlayerStopRes *message)
{
  assert(message->base.descriptor == &livepb__player__sc_player_stop_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t livepb__player__sc_player_stop_res__pack
                     (const Livepb__Player__ScPlayerStopRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &livepb__player__sc_player_stop_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t livepb__player__sc_player_stop_res__pack_to_buffer
                     (const Livepb__Player__ScPlayerStopRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &livepb__player__sc_player_stop_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Livepb__Player__ScPlayerStopRes *
       livepb__player__sc_player_stop_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Livepb__Player__ScPlayerStopRes *)
     protobuf_c_message_unpack (&livepb__player__sc_player_stop_res__descriptor,
                                allocator, len, data);
}
void   livepb__player__sc_player_stop_res__free_unpacked
                     (Livepb__Player__ScPlayerStopRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &livepb__player__sc_player_stop_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor livepb__player__sc_player_no_stream_notify__field_descriptors[2] =
{
  {
    NULL, /* CODE_SIZE */
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Livepb__Player__ScPlayerNoStreamNotify, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Livepb__Player__ScPlayerNoStreamNotify, stream_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const ProtobufCIntRange livepb__player__sc_player_no_stream_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor livepb__player__sc_player_no_stream_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Player__ScPlayerNoStreamNotify),
  2,
  livepb__player__sc_player_no_stream_notify__field_descriptors,
  NULL, /* CODE_SIZE */
  1,  livepb__player__sc_player_no_stream_notify__number_ranges,
  (ProtobufCMessageInit) livepb__player__sc_player_no_stream_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define livepb__player__sc_player_disconn_from_upstream_notify__field_descriptors NULL
#define livepb__player__sc_player_disconn_from_upstream_notify__field_indices_by_name NULL
#define livepb__player__sc_player_disconn_from_upstream_notify__number_ranges NULL
const ProtobufCMessageDescriptor livepb__player__sc_player_disconn_from_upstream_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Player__ScPlayerDisconnFromUpstreamNotify),
  0,
  livepb__player__sc_player_disconn_from_upstream_notify__field_descriptors,
  NULL, /* CODE_SIZE */
  0,  livepb__player__sc_player_disconn_from_upstream_notify__number_ranges,
  (ProtobufCMessageInit) livepb__player__sc_player_disconn_from_upstream_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor livepb__player__cs_player_statistics_frame_notify__field_descriptors[6] =
{
  {
    NULL, /* CODE_SIZE */
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, has_gop_sequence),
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, gop_sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, has_frame_rate),
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, frame_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, has_idr_count),
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, idr_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, has_slice_b_count),
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, slice_b_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, has_slice_p_count),
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, slice_p_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    NULL, /* CODE_SIZE */
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, has_average_download_speed),
    offsetof(Livepb__Player__CsPlayerStatisticsFrameNotify, average_download_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const ProtobufCIntRange livepb__player__cs_player_statistics_frame_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor livepb__player__cs_player_statistics_frame_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Player__CsPlayerStatisticsFrameNotify),
  6,
  livepb__player__cs_player_statistics_frame_notify__field_descriptors,
  NULL, /* CODE_SIZE */
  1,  livepb__player__cs_player_statistics_frame_notify__number_ranges,
  (ProtobufCMessageInit) livepb__player__cs_player_statistics_frame_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define livepb__player__cs_player_stop_req__field_descriptors NULL
#define livepb__player__cs_player_stop_req__field_indices_by_name NULL
#define livepb__player__cs_player_stop_req__number_ranges NULL
const ProtobufCMessageDescriptor livepb__player__cs_player_stop_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Player__CsPlayerStopReq),
  0,
  livepb__player__cs_player_stop_req__field_descriptors,
  NULL, /* CODE_SIZE */
  0,  livepb__player__cs_player_stop_req__number_ranges,
  (ProtobufCMessageInit) livepb__player__cs_player_stop_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define livepb__player__sc_player_stop_res__field_descriptors NULL
#define livepb__player__sc_player_stop_res__field_indices_by_name NULL
#define livepb__player__sc_player_stop_res__number_ranges NULL
const ProtobufCMessageDescriptor livepb__player__sc_player_stop_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  NULL,NULL,NULL,NULL, /* CODE_SIZE */
  sizeof(Livepb__Player__ScPlayerStopRes),
  0,
  livepb__player__sc_player_stop_res__field_descriptors,
  NULL, /* CODE_SIZE */
  0,  livepb__player__sc_player_stop_res__number_ranges,
  (ProtobufCMessageInit) livepb__player__sc_player_stop_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
